app = "rag_agent"
primary_region = "iad"

[env]
  DATA_DIR = "/data"
  HF_HOME = "/data/hf_cache"
  HF_HUB_OFFLINE = "0"

[mounts]
  source = "chatbot_data"
  destination = "/data"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = "shared-cpu-1x"
  memory = "1gb"